version: 0.0
os: linux
files:
   - source: /
     destination: /var/grassroot
permissions:
   - object: /var/grassroot
     pattern: "**"
     owner: root 
     group: root 
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installgrassroot.sh
      runas: root 
    - location: scripts/startgrassroot.sh
      runas: root 
   AfterInstall:
    - location: scripts/restartgrassroot.sh
      runas: root 
